In [1]:
from DeepGapSeq.simulation.deepgapseq_trace_generator import trace_generator
from DeepGapSeq.hmm_fitting.model import *
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from tqdm.notebook import tqdm


In [21]:
generator = trace_generator(n_colors=2, 
                            n_states=2,
                            n_frames=500,
                            n_traces=100,
                            export_mode="text_files",
                            reduce_memory=False,
                            )

training_data, training_labels, training_tmats = generator.generate_traces()

Generating traces...


100%|██████████| 100/100 [00:00<00:00, 246.48it/s]


Spent 0.4 s to generate 49 traces
Labels:  [0. 1.]
exporting txt files to: e:\OneDrive - Nexus365\Desktop\physics\Year 4\project\DeepGapSeq\src\deepgapseq_simulated_traces


In [22]:
simulated_traces = np.array(training_data)
labels = np.array(training_labels)
tmats = np.array(training_tmats)

lengths = np.array([generator.n_frames]*(int(len(labels)/generator.n_frames)))
# E_FRET = np.array(data[:,1]/(data[:,0]+data[:,1])).reshape(-1,1)

In [23]:
scores = []
for i in tqdm(range(simulated_traces.shape[0])):
    model = HMM_learn(n_states=2)
    model.fit(simulated_traces[i])
    predicted_states = model.predict(simulated_traces[i])
    scores.append(model.get_performance(predicted_states,labels[i]))
print(np.mean(scores))

  0%|          | 0/49 [00:00<?, ?it/s]

Model is not converging.  Current: 11403.972882387196 is not greater than 23832.84924410106. Delta is -12428.876361713865
Model is not converging.  Current: 16366.56564960567 is not greater than 30346.370305963097. Delta is -13979.804656357426


ValueError: 'covars' must be symmetric, positive-definite

In [24]:
tmats

array([[[0.96      , 0.04      ],
        [0.04      , 0.96      ]],

       [[0.95238095, 0.04761905],
        [0.04761905, 0.95238095]],

       [[0.98795181, 0.01204819],
        [0.01204819, 0.98795181]],

       [[0.97058824, 0.02941176],
        [0.02941176, 0.97058824]],

       [[0.9893617 , 0.0106383 ],
        [0.0106383 , 0.9893617 ]],

       [[0.98837209, 0.01162791],
        [0.01162791, 0.98837209]],

       [[0.98550725, 0.01449275],
        [0.01449275, 0.98550725]],

       [[0.        , 1.        ],
        [1.        , 0.        ]],

       [[0.98969072, 0.01030928],
        [0.01030928, 0.98969072]],

       [[0.98245614, 0.01754386],
        [0.01754386, 0.98245614]],

       [[0.98113208, 0.01886792],
        [0.01886792, 0.98113208]],

       [[0.98876404, 0.01123596],
        [0.01123596, 0.98876404]],

       [[0.9893617 , 0.0106383 ],
        [0.0106383 , 0.9893617 ]],

       [[0.98360656, 0.01639344],
        [0.01639344, 0.98360656]],

       [[0.98039216,

In [25]:
model.model.transmat_

array([[3.23984052e-19, 1.00000000e+00],
       [1.77555055e-18, 1.00000000e+00]])

array([[0.97192027, 0.02807973],
       [0.00323048, 0.99676952]])